apiVersion: v1
kind: Namespace
metadata:
  name: lab-csp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-csp
  namespace: lab-csp
  labels:
    app: backend-nest-test-csp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-csp
  template:
    metadata:
      labels:
        app: backend-nest-test-csp
    spec:
      containers:
      - name: backend-nest-test-csp
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-csp
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-svc
  namespace: lab-csp
  labels:
    app: backend-nest-svc
spec:
  selector:
     app: backend-nest-test-csp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3023
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-csp
  namespace: lab-csp
spec:
  ingressClassName: nginx
  rules:
  - host: csp.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-svc
            port:
              number: 80